# Generated by Django 3.0.2 on 2021-12-28 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120, null=True)),
                ('last_name', models.CharField(max_length=120, null=True)),
                ('email', models.CharField(max_length=256, null=True)),
                ('ph_num', models.CharField(max_length=20, null=True)),
                ('dob', models.DateField(null=True)),
                ('gender', models.CharField(max_length=30, null=True)),
                ('first_lang', models.CharField(max_length=60, null=True)),
            ],
        ),
    ]
